set(STYIO_BACKEND_SOURCES
  StyioCodeGen/CallableSpecializationObjectCache.cpp
  StyioCodeGen/GetTypeG.cpp
  StyioCodeGen/CodeGenG.cpp
  StyioCodeGen/LLVMEmission.cpp
  StyioCodeGen/CodeGenPulse.cpp
  StyioCodeGen/GetTypeIO.cpp
  StyioCodeGen/CodeGenIO.cpp
)
