function(styio_configure_library_target target_name)
  target_include_directories(${target_name} PUBLIC "${CMAKE_SOURCE_DIR}/src")
  target_include_directories(${target_name} SYSTEM PRIVATE ${LLVM_INCLUDE_DIRS})
  target_compile_definitions(${target_name} PRIVATE ${LLVM_DEFINITIONS_LIST})
endfunction()

function(styio_configure_binary_target target_name)
  target_include_directories(${target_name} SYSTEM PRIVATE ${LLVM_INCLUDE_DIRS})
  target_compile_definitions(${target_name} PRIVATE ${LLVM_DEFINITIONS_LIST})
endfunction()
